### ISSUE TITLE
hvad.WrongManager: for 'NewsEntry.slug'

### ISSUE THREAD

**Issue by schoera** [bitmazk/django-multilingual-news#9]
running the migrations (just after installing via pip) I get the following error (full stack trace below):

> hvad.exceptions.WrongManager: To access translated fields like 'slug' from an untranslated model, you must use a translation aware manager. For non-translatable models, you can get one using hvad.utils.get_translation_aware_manager.
> For translatable models, use the language() method.

Because I'm not into this translatable-stuff I can give no hint what could be wrong.
Thanks for any kind of help...

version infos:
> django: 1.9.2
> hvad: 1.5.0
> python 2.7.10

complete stracktrace:
```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/[path-to-site-packages]/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/[path-to-site-packages]/django/core/management/__init__.py", line 327, in execute
    django.setup()
  File "/[path-to-site-packages]/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/[path-to-site-packages]/django/apps/registry.py", line 115, in populate
    app_config.ready()
  File "/[path-to-site-packages]/django/contrib/admin/apps.py", line 22, in ready
    self.module.autodiscover()
  File "/[path-to-site-packages]/django/contrib/admin/__init__.py", line 26, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/[path-to-site-packages]/django/utils/module_loading.py", line 50, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/[path-to-site-packages]/multilingual_news/admin.py", line 47, in <module>
    admin.site.register(NewsEntry, NewsEntryAdmin)
  File "/[path-to-site-packages]/django/contrib/admin/sites.py", line 109, in register
    system_check_errors.extend(admin_obj.check())
  File "/[path-to-site-packages]/django/contrib/admin/options.py", line 113, in check
    return self.checks_class().check(self, **kwargs)
  File "/[path-to-site-packages]/django/contrib/admin/checks.py", line 495, in check
    errors = super(ModelAdminChecks, self).check(admin_obj)
  File "/[path-to-site-packages]/django/contrib/admin/checks.py", line 35, in check
    errors.extend(self._check_prepopulated_fields(admin_obj))
  File "/[path-to-site-packages]/django/contrib/admin/checks.py", line 350, in _check_prepopulated_fields
    for field_name, val in obj.prepopulated_fields.items()
  File "/[path-to-site-packages]/django/contrib/admin/checks.py", line 365, in _check_prepopulated_fields_key
    field = model._meta.get_field(field_name)
  File "/[path-to-site-packages]/hvad/utils.py", line 139, in __call__
    "method." % name)
hvad.exceptions.WrongManager: To access translated fields like 'slug' from an untranslated model, you must use a translation aware manager. For non-translatable models, you can get one using hvad.utils.get_translation_aware_manager.
For translatable models, use the language() method.

```

**Comment by Tyrdall** [comment]
Fixed in 2.6.3 :)
